language: go

go:
  - 1.14.x
  - 1.15.x
  - tip

os:
  - linux

services:
  - docker

branches:
  only:
  - master
  - develop

env:
  global:
    - IMAGE=essentialkaos/perfecto:centos7

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - docker pull "$IMAGE"
  - wget https://kaos.sh/perfecto/perfecto-docker
  - chmod +x perfecto-docker
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - make deps

script:
  - make all
  - ./perfecto-docker common/sonar.spec
