[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.5.0"

[[constraint]]
  name = "github.com/orcaman/concurrent-map"
  branch = "master"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  branch = "master"

[[constraint]]
  name = "pkg.re/essentialkaos/ek.v10"
  version = "10.12.0"

[prune]
  go-tests = true
  unused-packages = true
