[[constraint]]
  branch = "master"
  name = "github.com/orcaman/concurrent-map"

[[constraint]]
  name = "github.com/slack-go/slack"
  version = "0.6.4"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  branch = "master"

[[constraint]]
  name = "pkg.re/essentialkaos/ek.v12"
  version = "12.3.0"

[prune]
  go-tests = true
  unused-packages = true
