[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/orcaman/concurrent-map"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  version = "20180529.0.0"

[[constraint]]
  name = "pkg.re/essentialkaos/ek.v10"
  version = "10.8.0"

[prune]
  go-tests = true
  unused-packages = true
