################################################################################

# This Makefile generated by GoMakeGen 0.8.0 using next command:
# gomakegen .

################################################################################

.DEFAULT_GOAL := help
.PHONY = fmt all clean deps help

################################################################################

all: sonar ## Build all binaries

sonar: ## Build sonar binary
	go build sonar.go

install: ## Install binaries
	cp sonar /usr/bin/sonar

uninstall: ## Uninstall binaries
	rm -f /usr/bin/sonar

deps: ## Download dependencies
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v github.com/orcaman/concurrent-map
	go get -d -v pkg.re/essentialkaos/ek.v9
	go get -d -v pkg.re/essentialkaos/slack.v3
	go get -d -v pkg.re/valyala/fasthttp.v1

fmt: ## Format source code with gofmt
	find . -name "*.go" -exec gofmt -s -w {} \;

clean: ## Remove generated files
	rm -f sonar

help: ## Show this info
	@echo -e '\nSupported targets:\n'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[33m%-12s\033[0m %s\n", $$1, $$2}'
	@echo -e ''

################################################################################
